# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppEntropy_Cont <- function(vec, k = 3L, base = 10, NA_rm = FALSE) {
    .Call(`_spEDM_RcppEntropy_Cont`, vec, k, base, NA_rm)
}

RcppJoinEntropy_Cont <- function(mat, columns, k = 3L, base = 10, NA_rm = FALSE) {
    .Call(`_spEDM_RcppJoinEntropy_Cont`, mat, columns, k, base, NA_rm)
}

RcppMutualInformation_Cont <- function(mat, columns1, columns2, k = 3L, alg = 1L, normalize = FALSE, NA_rm = FALSE) {
    .Call(`_spEDM_RcppMutualInformation_Cont`, mat, columns1, columns2, k, alg, normalize, NA_rm)
}

RcppConditionalEntropy_Cont <- function(mat, target_columns, conditional_columns, k = 3L, base = 10, NA_rm = FALSE) {
    .Call(`_spEDM_RcppConditionalEntropy_Cont`, mat, target_columns, conditional_columns, k, base, NA_rm)
}

RcppEntropy_Disc <- function(vec, base = 10, NA_rm = FALSE) {
    .Call(`_spEDM_RcppEntropy_Disc`, vec, base, NA_rm)
}

RcppJoinEntropy_Disc <- function(mat, columns, base = 10, NA_rm = FALSE) {
    .Call(`_spEDM_RcppJoinEntropy_Disc`, mat, columns, base, NA_rm)
}

RcppMutualInformation_Disc <- function(mat, columns1, columns2, base = 10, NA_rm = FALSE) {
    .Call(`_spEDM_RcppMutualInformation_Disc`, mat, columns1, columns2, base, NA_rm)
}

RcppConditionalEntropy_Disc <- function(mat, target_columns, conditional_columns, base = 10, NA_rm = FALSE) {
    .Call(`_spEDM_RcppConditionalEntropy_Disc`, mat, target_columns, conditional_columns, base, NA_rm)
}

RcppSimplexForecast <- function(embedding, target, lib, pred, num_neighbors = 4L) {
    .Call(`_spEDM_RcppSimplexForecast`, embedding, target, lib, pred, num_neighbors)
}

RcppSMapForecast <- function(embedding, target, lib, pred, num_neighbors = 4L, theta = 1.0) {
    .Call(`_spEDM_RcppSMapForecast`, embedding, target, lib, pred, num_neighbors, theta)
}

RcppIntersectionCardinality <- function(embedding_x, embedding_y, lib, pred, num_neighbors = 4L, n_excluded = 0L, threads = 8L, parallel_level = 0L) {
    .Call(`_spEDM_RcppIntersectionCardinality`, embedding_x, embedding_y, lib, pred, num_neighbors, n_excluded, threads, parallel_level)
}

RcppLocateGridIndices <- function(curRow, curCol, totalRow, totalCol) {
    .Call(`_spEDM_RcppLocateGridIndices`, curRow, curCol, totalRow, totalCol)
}

RcppRowColFromGrid <- function(cellNum, totalCol) {
    .Call(`_spEDM_RcppRowColFromGrid`, cellNum, totalCol)
}

RcppLaggedVal4Grid <- function(mat, lagNum) {
    .Call(`_spEDM_RcppLaggedVal4Grid`, mat, lagNum)
}

RcppGenGridEmbeddings <- function(mat, E, tau) {
    .Call(`_spEDM_RcppGenGridEmbeddings`, mat, E, tau)
}

RcppGenGridNeighbors <- function(mat, lib, k) {
    .Call(`_spEDM_RcppGenGridNeighbors`, mat, lib, k)
}

RcppGenGridSymbolization <- function(mat, lib, pred, k) {
    .Call(`_spEDM_RcppGenGridSymbolization`, mat, lib, pred, k)
}

RcppDivideGrid <- function(mat, b, shape = 3L) {
    .Call(`_spEDM_RcppDivideGrid`, mat, b, shape)
}

RcppSLMUni4Grid <- function(mat, k = 4L, step = 20L, alpha = 0.77, escape_threshold = 1e10) {
    .Call(`_spEDM_RcppSLMUni4Grid`, mat, k, step, alpha, escape_threshold)
}

RcppSLMBi4Grid <- function(mat1, mat2, k = 4L, step = 20L, alpha_x = 0.625, alpha_y = 0.77, beta_xy = 0.05, beta_yx = 0.4, escape_threshold = 1e10) {
    .Call(`_spEDM_RcppSLMBi4Grid`, mat1, mat2, k, step, alpha_x, alpha_y, beta_xy, beta_yx, escape_threshold)
}

RcppSLMTri4Grid <- function(mat1, mat2, mat3, k = 4L, step = 20L, alpha_x = 0.625, alpha_y = 0.77, alpha_z = 0.55, beta_xy = 0.05, beta_xz = 0.05, beta_yx = 0.4, beta_yz = 0.4, beta_zx = 0.65, beta_zy = 0.65, escape_threshold = 1e10) {
    .Call(`_spEDM_RcppSLMTri4Grid`, mat1, mat2, mat3, k, step, alpha_x, alpha_y, alpha_z, beta_xy, beta_xz, beta_yx, beta_yz, beta_zx, beta_zy, escape_threshold)
}

RcppFNN4Grid <- function(mat, rt, eps, lib, pred, E, tau, threads) {
    .Call(`_spEDM_RcppFNN4Grid`, mat, rt, eps, lib, pred, E, tau, threads)
}

RcppSimplex4Grid <- function(source, target, lib, pred, E, b, tau, threads) {
    .Call(`_spEDM_RcppSimplex4Grid`, source, target, lib, pred, E, b, tau, threads)
}

RcppSMap4Grid <- function(source, target, lib, pred, theta, E, tau, b, threads) {
    .Call(`_spEDM_RcppSMap4Grid`, source, target, lib, pred, theta, E, tau, b, threads)
}

RcppMultiView4Grid <- function(xMatrix, yMatrix, lib, pred, E, tau, b, top, nvar, threads) {
    .Call(`_spEDM_RcppMultiView4Grid`, xMatrix, yMatrix, lib, pred, E, tau, b, top, nvar, threads)
}

RcppIC4Grid <- function(source, target, lib, pred, E, b, tau, exclude = 0L, threads = 8L, parallel_level = 0L) {
    .Call(`_spEDM_RcppIC4Grid`, source, target, lib, pred, E, b, tau, exclude, threads, parallel_level)
}

RcppGCCM4Grid <- function(xMatrix, yMatrix, libsizes, lib, pred, E, tau, b, simplex, theta, threads, parallel_level, progressbar) {
    .Call(`_spEDM_RcppGCCM4Grid`, xMatrix, yMatrix, libsizes, lib, pred, E, tau, b, simplex, theta, threads, parallel_level, progressbar)
}

RcppSCPCM4Grid <- function(xMatrix, yMatrix, zMatrix, libsizes, lib, pred, E, tau, b, simplex, theta, threads, parallel_level, cumulate, progressbar) {
    .Call(`_spEDM_RcppSCPCM4Grid`, xMatrix, yMatrix, zMatrix, libsizes, lib, pred, E, tau, b, simplex, theta, threads, parallel_level, cumulate, progressbar)
}

RcppGCMC4Grid <- function(xMatrix, yMatrix, libsizes, lib, pred, E, tau, b, r, threads, parallel_level, progressbar) {
    .Call(`_spEDM_RcppGCMC4Grid`, xMatrix, yMatrix, libsizes, lib, pred, E, tau, b, r, threads, parallel_level, progressbar)
}

RcppSGCSingle4Grid <- function(x, y, lib, pred, k, base = 2, symbolize = TRUE, normalize = FALSE) {
    .Call(`_spEDM_RcppSGCSingle4Grid`, x, y, lib, pred, k, base, symbolize, normalize)
}

RcppSGC4Grid <- function(x, y, lib, pred, block, k, threads, boot = 399L, base = 2, seed = 42L, symbolize = TRUE, normalize = FALSE, progressbar = TRUE) {
    .Call(`_spEDM_RcppSGC4Grid`, x, y, lib, pred, block, k, threads, boot, base, seed, symbolize, normalize, progressbar)
}

DetectMaxNumThreads <- function() {
    .Call(`_spEDM_DetectMaxNumThreads`)
}

OptEmbedDim <- function(Emat) {
    .Call(`_spEDM_OptEmbedDim`, Emat)
}

OptThetaParm <- function(Thetamat) {
    .Call(`_spEDM_OptThetaParm`, Thetamat)
}

OptICparm <- function(Emat) {
    .Call(`_spEDM_OptICparm`, Emat)
}

MatNotNAIndice <- function(mat, byrow = TRUE) {
    .Call(`_spEDM_MatNotNAIndice`, mat, byrow)
}

RcppLaggedNeighbor4Lattice <- function(nb, lagNum) {
    .Call(`_spEDM_RcppLaggedNeighbor4Lattice`, nb, lagNum)
}

RcppLaggedVal4Lattice <- function(vec, nb, lagNum) {
    .Call(`_spEDM_RcppLaggedVal4Lattice`, vec, nb, lagNum)
}

RcppGenLatticeEmbeddings <- function(vec, nb, E, tau) {
    .Call(`_spEDM_RcppGenLatticeEmbeddings`, vec, nb, E, tau)
}

RcppGenLatticeNeighbors <- function(vec, nb, lib, k) {
    .Call(`_spEDM_RcppGenLatticeNeighbors`, vec, nb, lib, k)
}

RcppGenLatticeSymbolization <- function(vec, nb, lib, pred, k) {
    .Call(`_spEDM_RcppGenLatticeSymbolization`, vec, nb, lib, pred, k)
}

RcppDivideLattice <- function(nb, b) {
    .Call(`_spEDM_RcppDivideLattice`, nb, b)
}

RcppSLMUni4Lattice <- function(vec, nb, k = 4L, step = 20L, alpha = 0.77, escape_threshold = 1e10) {
    .Call(`_spEDM_RcppSLMUni4Lattice`, vec, nb, k, step, alpha, escape_threshold)
}

RcppSLMBi4Lattice <- function(x, y, nb, k = 4L, step = 20L, alpha_x = 0.625, alpha_y = 0.77, beta_xy = 0.05, beta_yx = 0.4, escape_threshold = 1e10) {
    .Call(`_spEDM_RcppSLMBi4Lattice`, x, y, nb, k, step, alpha_x, alpha_y, beta_xy, beta_yx, escape_threshold)
}

RcppSLMTri4Lattice <- function(x, y, z, nb, k = 4L, step = 20L, alpha_x = 0.625, alpha_y = 0.77, alpha_z = 0.55, beta_xy = 0.05, beta_xz = 0.05, beta_yx = 0.4, beta_yz = 0.4, beta_zx = 0.65, beta_zy = 0.65, escape_threshold = 1e10) {
    .Call(`_spEDM_RcppSLMTri4Lattice`, x, y, z, nb, k, step, alpha_x, alpha_y, alpha_z, beta_xy, beta_xz, beta_yx, beta_yz, beta_zx, beta_zy, escape_threshold)
}

RcppFNN4Lattice <- function(vec, nb, rt, eps, lib, pred, E, tau, threads) {
    .Call(`_spEDM_RcppFNN4Lattice`, vec, nb, rt, eps, lib, pred, E, tau, threads)
}

RcppSimplex4Lattice <- function(source, target, nb, lib, pred, E, b, tau, threads) {
    .Call(`_spEDM_RcppSimplex4Lattice`, source, target, nb, lib, pred, E, b, tau, threads)
}

RcppSMap4Lattice <- function(source, target, nb, lib, pred, theta, E, tau, b, threads) {
    .Call(`_spEDM_RcppSMap4Lattice`, source, target, nb, lib, pred, theta, E, tau, b, threads)
}

RcppMultiView4Lattice <- function(x, y, nb, lib, pred, E, tau, b, top, nvar, threads) {
    .Call(`_spEDM_RcppMultiView4Lattice`, x, y, nb, lib, pred, E, tau, b, top, nvar, threads)
}

RcppIC4Lattice <- function(source, target, nb, lib, pred, E, b, tau, exclude = 0L, threads = 8L, parallel_level = 0L) {
    .Call(`_spEDM_RcppIC4Lattice`, source, target, nb, lib, pred, E, b, tau, exclude, threads, parallel_level)
}

RcppGCCM4Lattice <- function(x, y, nb, libsizes, lib, pred, E, tau, b, simplex, theta, threads, parallel_level, progressbar) {
    .Call(`_spEDM_RcppGCCM4Lattice`, x, y, nb, libsizes, lib, pred, E, tau, b, simplex, theta, threads, parallel_level, progressbar)
}

RcppSCPCM4Lattice <- function(x, y, z, nb, libsizes, lib, pred, E, tau, b, simplex, theta, threads, parallel_level, cumulate, progressbar) {
    .Call(`_spEDM_RcppSCPCM4Lattice`, x, y, z, nb, libsizes, lib, pred, E, tau, b, simplex, theta, threads, parallel_level, cumulate, progressbar)
}

RcppGCMC4Lattice <- function(x, y, nb, libsizes, lib, pred, E, tau, b, r, threads, parallel_level, progressbar) {
    .Call(`_spEDM_RcppGCMC4Lattice`, x, y, nb, libsizes, lib, pred, E, tau, b, r, threads, parallel_level, progressbar)
}

RcppSGCSingle4Lattice <- function(x, y, nb, lib, pred, k, base = 2, symbolize = TRUE, normalize = FALSE) {
    .Call(`_spEDM_RcppSGCSingle4Lattice`, x, y, nb, lib, pred, k, base, symbolize, normalize)
}

RcppSGC4Lattice <- function(x, y, nb, lib, pred, block, k, threads, boot = 399L, base = 2, seed = 42L, symbolize = TRUE, normalize = FALSE, progressbar = TRUE) {
    .Call(`_spEDM_RcppSGC4Lattice`, x, y, nb, lib, pred, block, k, threads, boot, base, seed, symbolize, normalize, progressbar)
}

RcppFactorial <- function(n) {
    .Call(`_spEDM_RcppFactorial`, n)
}

RcppCombine <- function(n, k) {
    .Call(`_spEDM_RcppCombine`, n, k)
}

RcppCombn <- function(vec, m) {
    .Call(`_spEDM_RcppCombn`, vec, m)
}

RcppGenSubsets <- function(vec) {
    .Call(`_spEDM_RcppGenSubsets`, vec)
}

RcppDigamma <- function(x) {
    .Call(`_spEDM_RcppDigamma`, x)
}

RcppLog <- function(x, base = 10) {
    .Call(`_spEDM_RcppLog`, x, base)
}

RcppMedian <- function(vec, NA_rm = FALSE) {
    .Call(`_spEDM_RcppMedian`, vec, NA_rm)
}

RcppMean <- function(vec, NA_rm = FALSE) {
    .Call(`_spEDM_RcppMean`, vec, NA_rm)
}

RcppMin <- function(vec, NA_rm = FALSE) {
    .Call(`_spEDM_RcppMin`, vec, NA_rm)
}

RcppMax <- function(vec, NA_rm = FALSE) {
    .Call(`_spEDM_RcppMax`, vec, NA_rm)
}

RcppSum <- function(vec, NA_rm = FALSE) {
    .Call(`_spEDM_RcppSum`, vec, NA_rm)
}

RcppVariance <- function(vec, NA_rm = FALSE) {
    .Call(`_spEDM_RcppVariance`, vec, NA_rm)
}

RcppCovariance <- function(vec1, vec2, NA_rm = FALSE) {
    .Call(`_spEDM_RcppCovariance`, vec1, vec2, NA_rm)
}

RcppMAE <- function(vec1, vec2, NA_rm = FALSE) {
    .Call(`_spEDM_RcppMAE`, vec1, vec2, NA_rm)
}

RcppRMSE <- function(vec1, vec2, NA_rm = FALSE) {
    .Call(`_spEDM_RcppRMSE`, vec1, vec2, NA_rm)
}

RcppCumSum <- function(vec) {
    .Call(`_spEDM_RcppCumSum`, vec)
}

RcppAbsDiff <- function(vec1, vec2) {
    .Call(`_spEDM_RcppAbsDiff`, vec1, vec2)
}

RcppSumNormalize <- function(vec, NA_rm = FALSE) {
    .Call(`_spEDM_RcppSumNormalize`, vec, NA_rm)
}

RcppArithmeticSeq <- function(from, to, length_out) {
    .Call(`_spEDM_RcppArithmeticSeq`, from, to, length_out)
}

RcppPearsonCor <- function(y, y_hat, NA_rm = FALSE) {
    .Call(`_spEDM_RcppPearsonCor`, y, y_hat, NA_rm)
}

RcppSpearmanCor <- function(y, y_hat, NA_rm = FALSE) {
    .Call(`_spEDM_RcppSpearmanCor`, y, y_hat, NA_rm)
}

RcppKendallCor <- function(y, y_hat, NA_rm = FALSE) {
    .Call(`_spEDM_RcppKendallCor`, y, y_hat, NA_rm)
}

RcppPartialCor <- function(y, y_hat, controls, NA_rm = FALSE, linear = FALSE) {
    .Call(`_spEDM_RcppPartialCor`, y, y_hat, controls, NA_rm, linear)
}

RcppPartialCorTrivar <- function(y, y_hat, control, NA_rm = FALSE, linear = FALSE) {
    .Call(`_spEDM_RcppPartialCorTrivar`, y, y_hat, control, NA_rm, linear)
}

RcppCorSignificance <- function(r, n, k = 0L) {
    .Call(`_spEDM_RcppCorSignificance`, r, n, k)
}

RcppCorConfidence <- function(r, n, k = 0L, level = 0.05) {
    .Call(`_spEDM_RcppCorConfidence`, r, n, k, level)
}

RcppDeLongAUCConfidence <- function(cases, controls, direction, level = 0.05) {
    .Call(`_spEDM_RcppDeLongAUCConfidence`, cases, controls, direction, level)
}

RcppCMCTest <- function(cases, direction, level = 0.05, num_samples = 0L) {
    .Call(`_spEDM_RcppCMCTest`, cases, direction, level, num_samples)
}

RcppDistance <- function(vec1, vec2, L1norm = FALSE, NA_rm = FALSE) {
    .Call(`_spEDM_RcppDistance`, vec1, vec2, L1norm, NA_rm)
}

RcppKNearestDistance <- function(vec1, k, L1norm = FALSE, NA_rm = FALSE) {
    .Call(`_spEDM_RcppKNearestDistance`, vec1, k, L1norm, NA_rm)
}

RcppMatDistance <- function(mat, L1norm = FALSE, NA_rm = FALSE) {
    .Call(`_spEDM_RcppMatDistance`, mat, L1norm, NA_rm)
}

RcppNeighborsNum <- function(vec, radius, equal = FALSE, L1norm = FALSE, NA_rm = FALSE) {
    .Call(`_spEDM_RcppNeighborsNum`, vec, radius, equal, L1norm, NA_rm)
}

RcppKNNIndice <- function(embedding_space, target_idx, k, lib) {
    .Call(`_spEDM_RcppKNNIndice`, embedding_space, target_idx, k, lib)
}

RcppDistKNNIndice <- function(dist_mat, target_idx, k, lib) {
    .Call(`_spEDM_RcppDistKNNIndice`, dist_mat, target_idx, k, lib)
}

RcppDistSortedIndice <- function(dist_mat, lib, include_self = FALSE) {
    .Call(`_spEDM_RcppDistSortedIndice`, dist_mat, lib, include_self)
}

RcppLinearTrendRM <- function(vec, xcoord, ycoord, NA_rm = FALSE) {
    .Call(`_spEDM_RcppLinearTrendRM`, vec, xcoord, ycoord, NA_rm)
}

RcppSVD <- function(X) {
    .Call(`_spEDM_RcppSVD`, X)
}

RcppDeLongPlacements <- function(cases, controls, direction) {
    .Call(`_spEDM_RcppDeLongPlacements`, cases, controls, direction)
}

RcppSpatialBlockBootstrap <- function(block, seed = 42L) {
    .Call(`_spEDM_RcppSpatialBlockBootstrap`, block, seed)
}

